version: 1
records:
  client-connection/browser-session:
    kind: grant
    payload:
      version: 1
      secret: TSX5DS6UNRm_C5lWKRAsJZxkR90SCNah8KgpF745D0s
refs:
  CAMELSTREAM_API_KEY: qaml_live_UUSL6hemg2KipuWZmkqjhqdM-9m7qOxN_Ji49ZbfyAQ
